botto/run_botto.py
I didn't think that bit of code through....
=> Fix error when there is no config file present

botto/tld_botto.py
(Hopefully) fixes meal window calculations when the period overlaps midnight
=> Fix timezone window calculations

.github/workflows/docker-publish.yml
I didn't mean to put that in the "deploy" step 🤦‍♂️
=> Move loading of cache to the "push" step

botto/reactions.py, botto/regexes.py, botto/run_botto.py, botto/tld_botto.py
=> Cleanup slightly

botto/config.py, botto/reactions.py, botto/regexes.py, botto/tld_botto.py
=> More generic way to add simple reactions

requirements.txt
Honestly, not entirely sure why it was working without this....
=> Add discord-py-slash-command to requirements.txt

botto/slash_commands.py
/unixtime provides the Unix Time conversion just for the sender
/time display it in local time for everyone
=> Add /time and /unixtime commands

botto/config.py
=> Support "I'm snail"

Dockerfile, requirements.txt
This will result in things breaking, but Tildy is probably a better testbed than Motto and we do kinda want them to react in threads....
=> Use the beta discord library

botto/message_helpers.py, botto/tld_botto.py
It's happening a little too quickly after confirmation.
=> Delay own message deletion by 1s

botto/food.py, botto/reactions.py
=> tildy now takes presents and gifts

botto/config.py, botto/reactions.py, botto/regexes.py, botto/tld_botto.py
=> Adds optional parties

botto/models.py, botto/slash_commands.py
"Discord ID" has to be a string
=> Another attempt at fixing adding new TLDers

botto/config.py
Resolves https://github.com/Lovely-Development-Team/TLDBotto/issues/152
=> NEW: Add please trigger [#152]

botto/config.py
snail regex is less permissive now
snail regex now accepts things like "pleeeeeeeeeeeeeeease"
fixes issue #158
=> improved please and snail regex

botto/extended_client.py, botto/message_checks.py, botto/slash_commands.py, botto/tld_botto.py
=> Attempt to use TLDer's display names

botto/reactions.py, botto/tld_botto.py
I'm not entirely sure what I was thinking with "oh yeah, if a reaction is removed then the vote isn't finished them and we should…unpin it" 🤦
=> Fix vote pinning

botto/mixins/clickup.py
Some hashtags would be recognised as existing in a different team — which we don't have access to — when they should just be ignored.
=> Fix some unrecognised hashtags still crashing Tildy

botto/regexes.py
As many `e`s, and an optional `s` at the end ;)
=> Add time(eeeee)s to the partay!

botto/message_helpers.py, botto/reactions.py, botto/tld_botto.py, botto/views/testflight_form.py
Not doing this is an error in Python 3.11
=> Use `asyncio.create_task` when calling `asyncio.wait`

botto/mixins/reaction_roles.py
We want to know that handler is actually getting called…
=> Add a debug log when user leaves a server

botto/storage/beta_testers/model.py
=> Fix KeyError when getting a ReactionRole without any apps

botto/views/testflight_form.py
This will actually block some valid emails, but anyone who's email really is `Joe\ Bloggs@example.com` or `a@b` can get in touch and explain themselves…
=> Update email validation

botto/views/testflight_form.py
Apparently I forgot the syntax 🤦‍♂️
=> Fix catching DNS resolution exceptions

botto/__init__.py
This time merging the right branch!!  🤦
=> Reduce logging level for discordpy
